/* eslint-disable no-irregular-whitespace */
import React from 'react';
import './information.css';

const Disclaimer = () => (
  <div
    className="info-section"
  >
    <p>
      {`Disclaimer

Updated at 2021-05-19


Splash Market hereby grants you access to splashmarket.io (“the Website”) and invites you to purchase the services offered here.


Definitions and key terms

To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:

  -Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
  -Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Splash Market, that is responsible for your information under this Disclaimer.
  -Service: refers to the service provided by Splash Market as described in the relative terms (if available) and on this platform.
  -Website: Splash Market."’s" site, which can be accessed via this URL: splashmarket.io
  -You: a person or entity that is registered with Splash Market to use the Services.
  

Limited liability

Splash Market endeavours to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.

The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Splash Market.

Particularly, all prices on the website are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.

Splash Market shall not bear any liability for hyperlinks to websites or services of third parties included on the website. From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.

Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.


Links to Other Websites Disclaimer

This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by Splash Market. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy and Terms of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.


Errors and Omissions Disclaimer

Splash Market is not responsible for any content, code or any other imprecision.

Splash Market does not provide warranties or guarantees.

In no event shall Splash Market be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Splash Market reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.


General Disclaimer

The Splash Market Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Splash Market is a distributor and not a publisher of the content supplied by third parties; as such, Splash Market exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Splash Market Service. Without limiting the foregoing, Splash Market specifically disclaims all warranties and representations in any content transmitted on or in connection with the Splash Market Service or on sites that may appear as links on the Splash Market Service, or in the products provided as a part of, or otherwise in connection with, the Splash Market Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Splash Market or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Splash Market does not warrant that the Splash Market Service will be uninterrupted, uncorrupted, timely, or error-free.


Copyright Disclaimer

All intellectual property rights concerning these materials are vested in Splash Market. Copying, distribution and any other use of these materials is not permitted without the written permission of Splash Market, except and only to the extent otherwise provided in regulations of mandatory law (such as the right to quote), unless otherwise stated for certain materials.


Affiliate Links Disclosure

Splash Market has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links from other websites/companies and products. These “affiliate links” are specific URLs that contain the affiliate's ID or username.

In compliance with the FTC guidelines, please assume the following about links and posts on this site:

  -Any/all of the links on Splash Market are affiliate links of which we receive a small commission from sales of certain items, but the price is the same for you. As Splash Market has grown, so have costs associated with running and maintaining it, and affiliate links are a way we help offset these costs.
  -If we post an affiliate link to a product, it is something that we personally use, support and would recommend without an affiliate link.
  -Unless otherwise noted, all reviews are of items we have purchased and we are not paid or compensated in any way.


Your Consent

We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.


Changes To Our Disclaimer

Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.


Contact Us

Don't hesitate to contact us if you have any questions regarding this Disclaimer.

 -Via Email:  saad786@splashnetwork.io

`}
    </p>

  </div>
);

export default Disclaimer;
